
server:
  port: 8801

spring:
  application:
    name: deptclient
  datasource:
    url: jdbc:mysql://DESKTOP-QLADQDP:3306/ssm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
